default: &default
  adapter: postgresql
  encoding: unicode
  user: root
  password: 123
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: rails_api_development
